server:
  servlet:
    context-path: /myspring
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://172.16.30.117:3306/myspring?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
#  redis:
#    database: 0 # Redis数据库索引（默认为0）
#    host: 192.168.57.11
#    port: 6379
#    password:
#    jedis:
#      pool:
#        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
#        max-wait:  -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 8   # 连接池中的最大空闲连接
#        min-idle: 0   # 连接池中的最小空闲连接
#    timeout: 50000ms # 连接超时时间（毫秒）
redis:
  host: 192.168.57.11
  maxTotal: 5
  maxIdle: 5
  testOnBorrow: true

mybatis:
  type-aliases-package: com.myexample.demo.domain
  mapper-locations: classpath*:mybatis/mapper/*.xml
  type-handlers-package: com.myexample.demo.config.handler
  base-packages: com.myexample.demo.mapper
#  configuration:
#    map-underscore-to-camel-case: true     #对下划线的处理


